aws.region=ap-south-1
aws.access-key-id=YOUR_ACCESS_KEY_ID
aws.secret-access-key=YOUR_ACCESS_KEY
aws.s3.bucket=_YOUR_BUCKET_NAME
aws.dynamodb.users-table=Users
aws.dynamodb.images-table=Images

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080
